version: "3.3"

services:
   algafood-db:
    image: mysql:8.0
    container_name: algafood-db
    restart: always
    ports:
       - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=algafood